(async()=>{
 const start=document.querySelector('#generalStart'),end=document.querySelector('#generalEnd'),cal=document.querySelector('#generalCalendar'),msg=document.querySelector('#availabilityMessage'),results=document.querySelector('#availabilityResults');
 const spaces=await getPublicSpaces(); const maps=new Map(); for(const s of spaces) maps.set(s.id,await getUnavailableDates(s.id));
 const today=localISODate(); let state={start:'',end:'',year:new Date().getFullYear(),month:new Date().getMonth()+1,target:'generalStart',open:false};
 const availableFor=iso=>spaces.some(s=>!maps.get(s.id)?.has(iso));
 const set=(el,iso)=>{if(!iso)return;el.value=displayDate(iso);el.dataset.iso=iso;};
 if(state.start) set(start,state.start);
 if(state.end) set(end,state.end);
 if(state.start){const p=dateToParts(state.start);state.year=p.y;state.month=p.m;}
 function render(){const first=new Date(state.year,state.month-1,1),days=new Date(state.year,state.month,0).getDate(),offset=(first.getDay()+6)%7;let cells='';for(let i=0;i<offset;i++)cells+='<span></span>';for(let d=1;d<=days;d++){const iso=isoFromParts(state.year,state.month,d),disabled=iso<today||!availableFor(iso);cells+=`<button class="calendar-day ${iso===state.start||iso===state.end?'selected':''}" ${disabled?'disabled':''} data-date="${iso}">${d}</button>`;}cal.innerHTML=`<div class="calendar-head"><button type="button" id="gp">‹</button><strong>${new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(first)}</strong><button type="button" id="gn">›</button></div><div class="calendar-weekdays"><span>L</span><span>M</span><span>X</span><span>J</span><span>V</span><span>S</span><span>D</span></div><div class="calendar-grid">${cells}</div>`;cal.querySelector('#gp').onclick=()=>{state.month--;if(state.month<1){state.month=12;state.year--;}render()};cal.querySelector('#gn').onclick=()=>{state.month++;if(state.month>12){state.month=1;state.year++;}render()};cal.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{const iso=b.dataset.date;if(state.target==='generalStart'){state.start=iso;state.end=state.end&&state.end>=iso?state.end:iso;set(start,state.start);set(end,state.end);}else{if(!state.start||iso<state.start){state.start=iso;state.end=iso;set(start,iso);set(end,iso)}else{state.end=iso;set(end,iso)}}cal.hidden=true;state.open=false;});}
 function placeGeneralCalendar(target){
   const input=document.querySelector('#'+target),wrap=input?.closest('.date-picker-wrap');
   if(wrap)wrap.insertAdjacentElement('afterend',cal);
 }
 document.querySelectorAll('.date-picker-toggle').forEach(b=>b.onclick=()=>{const target=b.dataset.target;if(state.open&&state.target===target&&!cal.hidden){cal.hidden=true;state.open=false;document.querySelector('#'+target)?.setAttribute('aria-expanded','false');return;}state.target=target;placeGeneralCalendar(state.target);const iso=parseUserDate(document.querySelector('#'+state.target).value)||today;const p=dateToParts(iso);state.year=p.y;state.month=p.m;cal.hidden=false;state.open=true;document.querySelector('#'+target)?.setAttribute('aria-expanded','true');render()});
 start.onfocus=()=>{state.target='generalStart';placeGeneralCalendar(state.target);cal.hidden=false;state.open=true;start.setAttribute('aria-expanded','true');render()};end.onfocus=()=>{state.target='generalEnd';placeGeneralCalendar(state.target);cal.hidden=false;state.open=true;end.setAttribute('aria-expanded','true');render()};
 document.querySelector('#searchAvailability').onclick=async()=>{const a=parseUserDate(start.value),b=parseUserDate(end.value);if(!a||!b||b<a){msg.textContent='Introduce un rango de fechas válido.';return;}const candidateSpaces=state.space?spaces.filter(s=>String(s.id)===String(state.space)):spaces; const available=candidateSpaces.filter(s=>{const m=maps.get(s.id)||new Map();return !rangeHasUnavailable(a,b,m)});if(!available.length){results.innerHTML='<div class="empty-state"><p>No hay espacios disponibles para estas fechas.</p><button class="btn btn-light" type="button" id="changeDates">Cambiar fechas</button><a class="btn btn-dark" href="espacios.html">Ver todos los espacios</a></div>';document.querySelector('#changeDates')?.addEventListener('click',()=>start.focus());msg.textContent='';return;}msg.textContent='';results.innerHTML=available.sort((x,y)=>x.name.localeCompare(y.name,'es')).map(s=>`<a class="space-tile" href="espacio.html?id=${encodeURIComponent(s.id)}#disponibilidad"><div class="space-tile-photo"><img src="${esc(s.image)}" alt="${esc(s.name)}"></div><div class="space-tile-info"><h2>${esc(s.name)}</h2><p>${esc(s.city)} · ${esc(s.province)}</p><div class="space-tile-price">${esc(priceRange(s))}</div><span class="btn btn-dark">Ver espacio y solicitar</span></div></a>`).join('');};
})();
