/* MiEspacioParaCelebrar — PREMIUM MASTER 2026-10-01
 * Capa de experiencia premium sobre la aplicación existente.
 * No sustituye app.js/admin.js: reutiliza su lógica y RPCs.
 */
(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n||0));
  const favKey='miespacio-premium-favorites';
  const getFav=()=>{try{return JSON.parse(localStorage.getItem(favKey)||'[]')}catch{return[]}};
  const setFav=a=>localStorage.setItem(favKey,JSON.stringify([...new Set(a.map(String))]));
  const isFav=id=>getFav().includes(String(id));
  const toggleFav=id=>{const a=getFav(),s=String(id),i=a.indexOf(s);i>=0?a.splice(i,1):a.push(s);setFav(a);return i<0};
  const toast=(msg,type='success')=>{let box=$('#premiumToast');if(!box){box=document.createElement('div');box.id='premiumToast';box.className='premium-toast';document.body.appendChild(box)}box.textContent=msg;box.dataset.type=type;box.classList.add('show');clearTimeout(box._t);box._t=setTimeout(()=>box.classList.remove('show'),2800)};
  const share=async(title,url)=>{try{if(navigator.share){await navigator.share({title,url});return}await navigator.clipboard.writeText(url);toast('Enlace copiado al portapapeles.')}catch{}}
  const routeLinks=(s)=>{if(!Number.isFinite(Number(s.latitude))||!Number.isFinite(Number(s.longitude)))return '';const d=`${s.latitude},${s.longitude}`;return `<div class="premium-route-actions"><a class="btn btn-light" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(d)}">Google Maps</a><a class="btn btn-light" target="_blank" rel="noopener" href="https://maps.apple.com/?daddr=${encodeURIComponent(d)}">Apple Maps</a></div>`};

  function injectGlobal(){
    const header=$('.site-header');
    if(header && !$('.premium-mobile-toggle',header)){
      const nav=$('nav',header); if(nav){const b=document.createElement('button');b.type='button';b.className='premium-mobile-toggle';b.setAttribute('aria-label','Abrir menú');b.textContent='☰';b.onclick=()=>nav.classList.toggle('premium-open');header.querySelector('.nav')?.classList.toggle('premium-menu-open');nav.addEventListener('click',e=>{if(e.target.closest('a'))nav.classList.remove('premium-open')});header.querySelector('.nav')?.appendChild(b)}
    }
    if(!$('#premiumToast')){const b=document.createElement('div');b.id='premiumToast';b.className='premium-toast';document.body.appendChild(b)}
  }

  async function home(){
    const root=$('#premiumHome'); if(!root)return;
    let spaces=[];try{spaces=window.getPublicSpaces?await window.getPublicSpaces():[]}catch{}
    if(!spaces.length && window.FALLBACK_SPACES)spaces=window.FALLBACK_SPACES;
    spaces=(spaces||[]).filter(s=>s.active!==false);
    const slides=spaces.slice(0,8);
    root.innerHTML=`<section class="premium-hero"><div class="premium-hero-media" id="premiumHeroMedia"></div><div class="premium-hero-overlay"></div><div class="container premium-hero-content"><p class="eyebrow">ESPACIOS PARA CELEBRAR</p><h1>Espacios únicos para momentos inolvidables</h1><p>Encuentra el lugar perfecto para tu evento en Lucena y vívelo como siempre lo has imaginado.</p><div class="premium-search"><label>¿Qué espacio?<select id="premiumSpaceSelect"><option value="">Todos los espacios</option>${spaces.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>Fecha de inicio<input id="premiumStart" type="date"></label><label>Fecha de fin<input id="premiumEnd" type="date"></label><button class="btn btn-gold" id="premiumSearchBtn">Buscar</button></div></div><button class="premium-hero-arrow left" id="heroPrev" aria-label="Anterior">‹</button><button class="premium-hero-arrow right" id="heroNext" aria-label="Siguiente">›</button><div class="premium-dots" id="heroDots"></div></section>
    <section class="premium-benefits"><div class="container premium-benefit-grid"><article><span>01</span><h3>Disponibilidad real</h3><p>Consulta fechas antes de enviar tu solicitud.</p></article><article><span>02</span><h3>Reserva sencilla</h3><p>Un proceso claro, paso a paso y sin complicaciones.</p></article><article><span>03</span><h3>Espacios verificados</h3><p>Información, fotografías, condiciones y servicios en un mismo lugar.</p></article><article><span>04</span><h3>Para cada celebración</h3><p>Cumpleaños, reuniones, empresas y momentos especiales.</p></article></div></section>
    <section class="section premium-section"><div class="container"><div class="premium-section-head"><div><p class="eyebrow">DESCUBRE</p><h2>Espacios que merecen ser celebrados</h2></div><a class="btn btn-light" href="espacios.html">Ver todos</a></div><div class="premium-featured-grid">${spaces.slice(0,3).map((s,i)=>`<a class="premium-featured-card" href="espacio.html?id=${encodeURIComponent(s.id)}"><img src="${esc(s.image||'assets/logo-miespacio-principal.png')}" alt="${esc(s.name)}" loading="${i?'lazy':'eager'}"><div><span>${esc(s.city||'Lucena')} · ${esc(s.province||'Córdoba')}</span><h3>${esc(s.name)}</h3><strong>${esc(window.priceRange?window.priceRange(s):'Consultar')}</strong></div></a>`).join('')}</div></div></section>
    <section class="section premium-soft"><div class="container premium-categories"><div><p class="eyebrow">TU CELEBRACIÓN</p><h2>¿Qué tienes en mente?</h2><p class="muted">Explora y encuentra un espacio que encaje con tu momento.</p></div><div class="premium-category-grid">${['Cumpleaños','Comuniones','Bautizos','Reuniones familiares','Eventos de empresa','Celebraciones privadas'].map(x=>`<a href="espacios.html?evento=${encodeURIComponent(x)}" class="premium-category">${esc(x)}<span>→</span></a>`).join('')}</div></div></section>
    <section class="section"><div class="container premium-owner-cta"><div><p class="eyebrow">¿TIENES UN ESPACIO?</p><h2>Haz que también forme parte de la celebración.</h2><p class="muted">Presenta tu espacio y estudiaremos contigo cómo incorporarlo a la plataforma.</p></div><a class="btn btn-dark" href="incluir-espacio.html">Quiero incluir mi espacio</a></div></section>`;
    let idx=0;const media=$('#premiumHeroMedia'),dots=$('#heroDots');
    const paint=()=>{if(!slides.length){media.innerHTML='<div class="premium-hero-empty"></div>';return}const s=slides[idx];media.innerHTML=`<img src="${esc(s.image||'assets/logo-miespacio-principal.png')}" alt="${esc(s.name)}">`;dots.innerHTML=slides.map((_,i)=>`<button class="${i===idx?'active':''}" data-i="${i}" aria-label="Imagen ${i+1}"></button>`).join('');$$('[data-i]',dots).forEach(b=>b.onclick=()=>{idx=Number(b.dataset.i);paint()})};paint();$('#heroPrev')?.addEventListener('click',()=>{idx=(idx-1+slides.length)%slides.length;paint()});$('#heroNext')?.addEventListener('click',()=>{idx=(idx+1)%slides.length;paint()});if(slides.length>1)setInterval(()=>{idx=(idx+1)%slides.length;paint()},6500);
    $('#premiumSearchBtn')?.addEventListener('click',()=>{const p=new URLSearchParams();const id=$('#premiumSpaceSelect').value,s=$('#premiumStart').value,e=$('#premiumEnd').value;if(id)p.set('space',id);if(s)p.set('start',s);if(e)p.set('end',e);location.href=`disponibilidad.html?${p}`});
  }

  async function spaces(){
    const grid=$('#spacesGrid');if(!grid)return;const spaces=window.__publicSpaces||await window.getPublicSpaces?.()||[];window.__publicSpaces=spaces;
    const section=grid.parentElement; if(!$('#premiumFilters')){const wrap=document.createElement('div');wrap.id='premiumFilters';wrap.className='premium-filters';wrap.innerHTML=`<div class="premium-filter-row"><input id="filterText" placeholder="Buscar espacio…" aria-label="Buscar espacio"><select id="filterEvent"><option value="">Tipo de evento</option>${['Cumpleaños','Comuniones','Bautizos','Reuniones familiares','Eventos de empresa','Celebraciones privadas'].map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="filterPrice"><option value="">Precio máximo</option><option value="100">100 €</option><option value="150">150 €</option><option value="200">200 €</option><option value="300">300 €</option></select><button class="btn btn-light" id="clearFilters">Limpiar</button></div><div class="premium-filter-meta"><span id="resultCount"></span><div><button class="btn btn-light" id="compareBtn">Comparar seleccionados</button><a class="btn btn-light" href="favoritos.html">♥ Favoritos</a></div></div>`;section.insertBefore(wrap,grid)}
    const render=()=>{const q=$('#filterText').value.trim().toLowerCase(),max=Number($('#filterPrice').value||Infinity),event=$('#filterEvent').value;const out=spaces.filter(s=>(!q||String(s.name).toLowerCase().includes(q)||String(s.city).toLowerCase().includes(q))&&(!max||Number(s.priceWeekday||0)<=max)&&(!event||JSON.stringify(s).toLowerCase().includes(event.toLowerCase())));$('#resultCount').textContent=`${out.length} espacio${out.length===1?'':'s'}`;grid.innerHTML=out.length?out.map(s=>`<article class="premium-space-card"><a href="espacio.html?id=${encodeURIComponent(s.id)}" class="premium-space-link"><div class="premium-space-photo"><img src="${esc(s.image)}" alt="${esc(s.name)}" loading="lazy"><span class="premium-badge">Disponible para solicitar</span></div><div class="premium-space-body"><div><span class="premium-kicker">${esc(s.city||'Lucena')} · ${esc(s.province||'Córdoba')}</span><h2>${esc(s.name)}</h2><p>${esc((s.description||'').slice(0,130))}</p></div><strong>${esc(window.priceRange?window.priceRange(s):'Consultar')}</strong></div></a><div class="premium-card-actions"><button class="premium-icon-btn fav-btn ${isFav(s.id)?'active':''}" data-fav="${esc(s.id)}" aria-label="${isFav(s.id)?'Quitar de favoritos':'Añadir a favoritos'}">♥</button><label class="premium-compare"><input type="checkbox" data-compare="${esc(s.id)}"> Comparar</label></div></article>`).join(''):'<div class="premium-empty"><h3>No encontramos espacios</h3><p>Prueba a cambiar los filtros o consultar otra fecha.</p></div>';
      $$('[data-fav]',grid).forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const yes=toggleFav(b.dataset.fav);b.classList.toggle('active',yes);toast(yes?'Añadido a favoritos':'Eliminado de favoritos')});
    };['filterText','filterEvent','filterPrice'].forEach(id=>$('#'+id).addEventListener('input',render));$('#clearFilters').onclick=()=>{$('#filterText').value='';$('#filterEvent').value='';$('#filterPrice').value='';render()};$('#compareBtn').onclick=()=>{const ids=$$('[data-compare]:checked',grid).map(x=>x.dataset.compare);if(ids.length<2){toast('Selecciona al menos dos espacios para comparar','error');return}localStorage.setItem('miespacio-premium-compare',JSON.stringify(ids));location.href='comparar.html'};render();
  }

  async function detail(){
    const root=$('#spaceDetail');if(!root)return;await new Promise(r=>setTimeout(r,150));const s=window.__publicSpaces?.find(x=>String(x.id)===new URLSearchParams(location.search).get('id'))||null;
    if(!s)return;const head=$('.space-detail-heading',root);if(head&&!$('.premium-detail-tools',head)){const d=document.createElement('div');d.className='premium-detail-tools';d.innerHTML=`<button class="btn btn-light" id="detailFav">♥ ${isFav(s.id)?'Guardado':'Guardar'}</button><button class="btn btn-light" id="detailShare">Compartir</button>`;head.appendChild(d);$('#detailFav').onclick=()=>{const yes=toggleFav(s.id);$('#detailFav').innerHTML=`♥ ${yes?'Guardado':'Guardar'}`;toast(yes?'Espacio guardado':'Espacio eliminado de favoritos')};$('#detailShare').onclick=()=>share(s.name,location.href)}
    const map=$('#spaceMap')?.parentElement;if(map&&!$('.premium-route-box',map)){const box=document.createElement('div');box.className='premium-route-box';box.innerHTML=`<div><p class="eyebrow">CÓMO LLEGAR</p><h3>Encuentra el espacio fácilmente</h3><p class="muted">Abre la navegación en tu aplicación de mapas habitual.</p></div>${routeLinks(s)}`;map.appendChild(box)}
    const gallery=$('.gallery',root);if(gallery&&!gallery.dataset.lightbox){gallery.dataset.lightbox='1';gallery.addEventListener('click',e=>{const img=e.target.closest('img');if(!img)return;const m=document.createElement('div');m.className='premium-lightbox';m.innerHTML=`<button class="premium-lightbox-close" aria-label="Cerrar">×</button><img src="${img.src}" alt="${esc(img.alt)}">`;m.onclick=()=>m.remove();document.body.appendChild(m)})}
  }

  function favorites(){const root=$('#favoritesRoot');if(!root)return;const ids=getFav();const spaces=window.__publicSpaces||[];root.innerHTML=`<div class="premium-section-head"><div><p class="eyebrow">GUARDADOS</p><h1>Mis espacios favoritos</h1><p class="muted">Tus favoritos se guardan en este dispositivo.</p></div><a class="btn btn-light" href="espacios.html">Explorar espacios</a></div><div class="premium-featured-grid">${spaces.filter(s=>ids.includes(String(s.id))).map(s=>`<a class="premium-featured-card" href="espacio.html?id=${encodeURIComponent(s.id)}"><img src="${esc(s.image)}" alt="${esc(s.name)}"><div><span>${esc(s.city||'')}</span><h3>${esc(s.name)}</h3><strong>${esc(window.priceRange?window.priceRange(s):'Consultar')}</strong></div></a>`).join('')||'<div class="premium-empty"><h3>Aún no tienes favoritos</h3><p>Guarda los espacios que quieras comparar después.</p></div>'}</div>`}

  function compare(){const root=$('#compareRoot');if(!root)return;const ids=JSON.parse(localStorage.getItem('miespacio-premium-compare')||'[]');const spaces=(window.__publicSpaces||[]).filter(s=>ids.includes(String(s.id)));const rows=[['Precio desde',s=>window.priceRange?window.priceRange(s):'Consultar'],['Capacidad',s=>s.capacity||'Consultar'],['Limpieza',s=>s.cleaningAvailable?'Disponible':'No indicada'],['Horario',s=>s.hours||'Consultar'],['Ubicación',s=>`${s.city||''} · ${s.province||''}`]];root.innerHTML=`<div class="premium-section-head"><div><p class="eyebrow">COMPARAR</p><h1>Compara tus espacios</h1></div><a class="btn btn-light" href="espacios.html">Añadir espacios</a></div>${spaces.length?`<div class="premium-compare-table"><table><thead><tr><th>Característica</th>${spaces.map(s=>`<th><img src="${esc(s.image)}" alt=""><strong>${esc(s.name)}</strong></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r[0])}</th>${spaces.map(s=>`<td>${esc(r[1](s))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="premium-empty"><h3>No hay espacios seleccionados</h3><a class="btn btn-dark" href="espacios.html">Explorar espacios</a></div>'}`}

  function enhanceAvailability(){const box=$('.availability-search-card');if(!box||$('#premiumAvailabilityNote'))return;const n=document.createElement('div');n.id='premiumAvailabilityNote';n.className='premium-info-banner';n.innerHTML='<strong>Busca varias fechas de una vez.</strong><span>Solo mostraremos espacios disponibles durante todo el periodo seleccionado.</span>';box.prepend(n)}

  function ownerDashboard(){const root=$('#premiumOwnerRoot');if(!root)return;root.innerHTML=`<div class="premium-dashboard-head"><div><p class="eyebrow">ÁREA DEL PROPIETARIO</p><h1>Gestiona tus espacios</h1><p class="muted">Reservas, calendario, precios, fotografías y condiciones en un solo lugar.</p></div><a class="btn btn-dark" href="area-privada.html">Abrir área actual</a></div><div class="premium-kpi-grid"><article><span>Reservas</span><strong id="ownerKpiBookings">—</strong><small>Próximas solicitudes</small></article><article><span>Espacios</span><strong id="ownerKpiSpaces">—</strong><small>Activos</small></article><article><span>Ocupación</span><strong id="ownerKpiOccupancy">—</strong><small>Indicador preparado</small></article><article><span>Avisos</span><strong id="ownerKpiAlerts">0</strong><small>Revisar comunicaciones</small></article></div><div class="premium-console-grid"><a href="area-privada.html" class="premium-console-card"><b>Calendario</b><span>Consulta reservas y bloquea fechas.</span></a><a href="area-privada.html" class="premium-console-card"><b>Mis espacios</b><span>Precios, servicios, fotos y condiciones.</span></a><a href="area-privada.html" class="premium-console-card"><b>Solicitudes</b><span>Acepta, modifica o cancela reservas.</span></a><a href="incluir-espacio.html" class="premium-console-card"><b>Ayuda</b><span>Contacta con la plataforma.</span></a></div>`}

  function adminDashboard(){const root=$('#premiumAdminRoot');if(!root)return;root.innerHTML=`<div class="premium-dashboard-head"><div><p class="eyebrow">CENTRO DE CONTROL</p><h1>Administración Premium</h1><p class="muted">Control de espacios, propietarios, reservas, comunicaciones y actividad.</p></div><a class="btn btn-dark" href="admin.html">Abrir administración actual</a></div><div class="premium-kpi-grid"><article><span>Espacios</span><strong id="admKpiSpaces">—</strong><small>Catálogo</small></article><article><span>Propietarios</span><strong id="admKpiOwners">—</strong><small>Activos</small></article><article><span>Reservas</span><strong id="admKpiBookings">—</strong><small>Histórico</small></article><article><span>Comunicaciones</span><strong id="admKpiEmails">—</strong><small>Cola / historial</small></article></div><div class="premium-console-grid"><a href="admin.html" class="premium-console-card"><b>Espacios</b><span>Crear, publicar, editar y gestionar fotografías.</span></a><a href="admin.html" class="premium-console-card"><b>Propietarios</b><span>Altas, datos y seguimiento.</span></a><a href="admin.html" class="premium-console-card"><b>Reservas</b><span>Supervisar y modificar solicitudes.</span></a><a href="admin.html" class="premium-console-card"><b>Comunicaciones</b><span>Emails, encuestas e incidencias.</span></a></div>`}

  async function loadAdminKpis(){const client=window.getClient?await window.getClient():null;if(!client)return;const calls=[client.rpc('admin_get_spaces'),client.rpc('admin_get_owners'),client.rpc('admin_get_bookings'),client.rpc('admin_get_email_history')];const [a,b,c,d]=await Promise.all(calls);if($('#admKpiSpaces'))$('#admKpiSpaces').textContent=(a.data||[]).length;if($('#admKpiOwners'))$('#admKpiOwners').textContent=(b.data||[]).length;if($('#admKpiBookings'))$('#admKpiBookings').textContent=(c.data||[]).length;if($('#admKpiEmails'))$('#admKpiEmails').textContent=(d.data||[]).length}
  async function guardPrivate(role){const client=window.getClient?await window.getClient():null;if(!client){location.href='acceso.html';return null}const {data:{user}}=await client.auth.getUser();if(!user){location.href='acceso.html';return null}const {data:profile}=await client.from('profiles').select('role,active').eq('id',user.id).maybeSingle();if(!profile||profile.active!==true||profile.role!==role){location.href='acceso.html';return null}return client}

  async function loadOwnerKpis(){const client=window.getClient?await window.getClient():null;if(!client)return;const [a,b]=await Promise.all([client.rpc('get_owner_spaces'),client.rpc('get_owner_bookings')]);if($('#ownerKpiSpaces'))$('#ownerKpiSpaces').textContent=(a.data||[]).filter(s=>s.owner_active!==false&&s.admin_enabled!==false).length;if($('#ownerKpiBookings'))$('#ownerKpiBookings').textContent=(b.data||[]).filter(x=>['pending','confirmed'].includes(x.booking_status)).length}

  async function boot(){injectGlobal();const page=document.body.dataset.page||'';if(page==='home')await home();if(page==='spaces')await spaces();if(page==='detail')await detail();if(page==='favorites'){window.__publicSpaces=await (window.getPublicSpaces?window.getPublicSpaces():Promise.resolve([]));favorites()}if(page==='compare'){window.__publicSpaces=await (window.getPublicSpaces?window.getPublicSpaces():Promise.resolve([]));compare()}if(page==='availability')enhanceAvailability();if(page==='owner'){const c=await guardPrivate('owner');if(c){ownerDashboard();await loadOwnerKpis()}}if(page==='admin'){const c=await guardPrivate('admin');if(c){adminDashboard();await loadAdminKpis()}}}
  document.addEventListener('DOMContentLoaded',boot);
  window.PremiumMaster={toast,toggleFav,isFav,getFav,share};
})();
