name: Prueba scheduler GitHub

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar scheduler
        run: |
          echo "SCHEDULER FUNCIONA"
          date -u
